### PR TITLE
Update iOS and OS X deployment targets

### PR DESCRIPTION
**Pull request by a2**

### CODE REVIEW

**Comment by felixvisee** [comment]
Depends on https://github.com/robb/Monocle/pull/3.

**Comment by robrix** [comment]
https://github.com/robb/Monocle/pull/3 has been merged.

**Comment by robrix** [comment]
And tagged: https://github.com/robb/Monocle/releases/tag/0.0.2

**Comment by felixvisee** [comment]
Thanks @a2 and @robrix :)

**Comment by robrix** [comment]
You’re very welcome.

**Pull request merged**
