### PR TITLE
Update for Swift 2.0

### PR DESCRIPTION
**Pull request by a2**
You'll need to merge robb/Monocle#4 and felixjendrusch/ValueTransformer#2 before this one, and update the `Cartfile` to point to the updated tags.

### CODE REVIEW

**Comment by felixvisee** [comment]
Waiting for robb/Monocle#4 to be merged.

**Comment by a2** [comment]
Updated the Cartfile. @felixjendrusch, do you want to tag a release or create a _swift-2.0_ branch?

**Comment by felixvisee** [comment]
I would go for a branch until there is a release for Monocle. Also made you a collaborator on this project, feel free to create that branch :) Thanks for your contributions!

**Comment by a2** [comment]
Created a [swift-2.0 branch](https://github.com/felixjendrusch/Pistachio/tree/swift-2.0).

**Pull request closed without merging**
